import { LootBox } from "../types";
import { LogoService } from "./logoService";

const now = Date.now();
const oneHour = 60 * 60 * 1000;
const oneDay = 24 * oneHour;

export const mockLootBoxes: LootBox[] = [
  {
    id: "1",
    title: "Coffee Delight",
    latitude: 37.7849,
    longitude: -122.4094,
    category: "restaurant",
    businessName: "Blue Bottle Coffee",
    businessLogo: LogoService.getBusinessLogo("Blue Bottle Coffee"),
    dropTime: now + 30 * 60 * 1000,
    isActive: false,
    coupon: {
      id: "c1",
      code: "COFFEE50",
      title: "50% Off Any Coffee",
      description: "Get half off any coffee drink",
      discountType: "percentage",
      value: "50%",
      expiresAt: now + 7 * oneDay,
      businessName: "Blue Bottle Coffee",
      businessLogo: LogoService.getBusinessLogo("Blue Bottle Coffee"),
    },
  },
  {
    id: "2",
    title: "Pizza Party",
    latitude: 37.7858,
    longitude: -122.4064,
    category: "restaurant",
    businessName: "Tony's Pizzeria",
    businessLogo: LogoService.getBusinessLogo("Tony's Pizzeria"),
    dropTime: now + 2 * oneHour,
    isActive: false,
    coupon: {
      id: "c2",
      code: "PIZZA20",
      title: "20% Off Large Pizza",
      description: "Discount on any large pizza",
      discountType: "percentage",
      value: "20%",
      expiresAt: now + 14 * oneDay,
      businessName: "Tony's Pizzeria",
      businessLogo: LogoService.getBusinessLogo("Tony's Pizzeria"),
    },
  },
  {
    id: "3",
    title: "Free Smoothie",
    latitude: 37.7839,
    longitude: -122.4089,
    category: "restaurant",
    businessName: "Juice Bar",
    businessLogo: LogoService.getBusinessLogo("Juice Bar"),
    dropTime: now - 10 * 60 * 1000,
    isActive: true,
    coupon: {
      id: "c3",
      code: "FREESMOOTHIE",
      title: "Free Small Smoothie",
      description: "Redeem for a complimentary small smoothie",
      discountType: "freeItem",
      value: "Free",
      expiresAt: now + 3 * oneDay,
      businessName: "Juice Bar",
      businessLogo: LogoService.getBusinessLogo("Juice Bar"),
    },
  },
  {
    id: "4",
    title: "Bookstore Special",
    latitude: 37.7869,
    longitude: -122.4074,
    category: "retail",
    businessName: "City Lights Books",
    businessLogo: LogoService.getBusinessLogo("City Lights Books"),
    dropTime: now + 4 * oneHour,
    isActive: false,
    coupon: {
      id: "c4",
      code: "BOOK15",
      title: "$15 Off Purchase",
      description: "Save $15 on purchases over $50",
      discountType: "fixed",
      value: "$15",
      expiresAt: now + 30 * oneDay,
      businessName: "City Lights Books",
      businessLogo: LogoService.getBusinessLogo("City Lights Books"),
    },
  },
  {
    id: "5",
    title: "Gym Membership Deal",
    latitude: 37.7829,
    longitude: -122.4104,
    category: "services",
    businessName: "FitZone Gym",
    businessLogo: LogoService.getBusinessLogo("FitZone Gym"),
    dropTime: now - 5 * 60 * 1000,
    isActive: true,
    coupon: {
      id: "c5",
      code: "GYM30",
      title: "30% Off Monthly Pass",
      description: "First month at 30% discount",
      discountType: "percentage",
      value: "30%",
      expiresAt: now + 10 * oneDay,
      businessName: "FitZone Gym",
      businessLogo: LogoService.getBusinessLogo("FitZone Gym"),
    },
  },
  {
    id: "6",
    title: "Movie Night",
    latitude: 37.7879,
    longitude: -122.4054,
    category: "entertainment",
    businessName: "Cinema Palace",
    businessLogo: LogoService.getBusinessLogo("Cinema Palace"),
    dropTime: now + 6 * oneHour,
    isActive: false,
    coupon: {
      id: "c6",
      code: "MOVIE2FOR1",
      title: "Buy One Get One Free",
      description: "Second ticket free on weekdays",
      discountType: "freeItem",
      value: "BOGO",
      expiresAt: now + 7 * oneDay,
      businessName: "Cinema Palace",
      businessLogo: LogoService.getBusinessLogo("Cinema Palace"),
    },
  },
];

